/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hydon
 */

import java.awt.Image;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;

public final class AnaForm extends javax.swing.JFrame {
   
    private DefaultTableModel FaturaModel = new DefaultTableModel();
    
    private Object[] faturaSutun = {"Fatura Kayit No", "Fatura Turu", "Fatura Tarihi", "Fatura Odeme Tarihi", 
                                   "Fatura Miktari", "Odemeye Ait Dekont"};//sutun isimlerini yazmak icin bir object olusturuyoruz

    private Object[] faturaSatir = new Object[6];

    private DefaultTableModel GarantiBelgesiModel = new DefaultTableModel();
    private Object[] garantiBelgesiSutun = {"Garanti Belge No", "Urunun Turu", "Urunun Markasi", "Urunun Modeli", "Urunun Adi", 
                                           "Urunun Seri Numarasi", "Urunun Garanti Bitis Tarihi", "Urunun Faturasi"};//sutun isimlerini yazmak icin bir object olusturuyoruz

    static Object[] garantiBelgesiSatir = new Object[8];
    /**
     *
     *
     * Creates new form frm1
     */
    public AnaForm() 
    {
        initComponents();//formun ayarları bu fonksiyonun icinde bu sayede form olusur
        FormunIconunuAyarla();//baslangicta formun iconu ayarlanir
        TablolariGetir();//tablolar getirillir
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        BtnFaturaIslemleri = new javax.swing.JButton();
        label1 = new java.awt.Label();
        BtnGarantiBelgesiIslemleri = new javax.swing.JButton();
        label2 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnTabloyuYenile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Evim");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        setForeground(java.awt.Color.black);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(116, 212, 192));
        jPanel3.setRequestFocusEnabled(false);

        BtnFaturaIslemleri.setBackground(new java.awt.Color(255, 216, 166));
        BtnFaturaIslemleri.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnFaturaIslemleri.setText("Fatura İslemleri");
        BtnFaturaIslemleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFaturaIslemleriActionPerformed(evt);
            }
        });

        label1.setBackground(new java.awt.Color(116, 212, 192));
        label1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label1.setText("Faturalarınız:");

        BtnGarantiBelgesiIslemleri.setBackground(new java.awt.Color(255, 216, 166));
        BtnGarantiBelgesiIslemleri.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnGarantiBelgesiIslemleri.setText("Garanti Belgesi İslemleri");
        BtnGarantiBelgesiIslemleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGarantiBelgesiIslemleriActionPerformed(evt);
            }
        });

        label2.setBackground(new java.awt.Color(116, 212, 192));
        label2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label2.setText("Garanti Belgeleriniz:");

        jScrollPane1.setEnabled(false);

        jTable3.setModel(FaturaModel);
        jTable3.setEnabled(false);
        jScrollPane1.setViewportView(jTable3);

        jScrollPane3.setEnabled(false);

        jTable1.setModel(GarantiBelgesiModel);
        jTable1.setEnabled(false);
        jScrollPane3.setViewportView(jTable1);

        BtnTabloyuYenile.setBackground(new java.awt.Color(255, 216, 166));
        BtnTabloyuYenile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnTabloyuYenile.setText("Tabloyu Yenile");
        BtnTabloyuYenile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTabloyuYenileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BtnFaturaIslemleri, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnTabloyuYenile, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnGarantiBelgesiIslemleri))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnFaturaIslemleri)
                    .addComponent(BtnTabloyuYenile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(BtnGarantiBelgesiIslemleri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGarantiBelgesiIslemleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGarantiBelgesiIslemleriActionPerformed
        // TODO add your handling code here:
        GarantiIslemleriFormu garantiIslemleriFormu = new GarantiIslemleriFormu();
        garantiIslemleriFormu.setVisible(true);//garanti islemeleri formunu acar 
    }//GEN-LAST:event_BtnGarantiBelgesiIslemleriActionPerformed

    private void BtnFaturaIslemleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFaturaIslemleriActionPerformed
        // TODO add your handling code here:
        FaturaIslemleriFormu faturaIslemleriFormu = new FaturaIslemleriFormu();
        faturaIslemleriFormu.setVisible(true);//fatura islemeleri formunu acar
    }//GEN-LAST:event_BtnFaturaIslemleriActionPerformed

    private void BtnTabloyuYenileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTabloyuYenileActionPerformed
        // TODO add your handling code here:
        TablolariGetir();//tabloyu en son halini getirir
    }//GEN-LAST:event_BtnTabloyuYenileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaForm().setVisible(true);
            }
        });
    }
    
        private void TablolariGetir() //tablolar veri tabanından donen tablolara gore doldurulur
    {
        FaturaModel.setRowCount(0);//varsa eski tablo sifirlanir
        VeritabaniBaglanti baglanti = new VeritabaniBaglanti();
        ResultSet sonEklenenFaturaSonuc = baglanti.SonEklenenFaturalar();
        FaturaModel.setColumnIdentifiers(faturaSutun);//yukarıda tanimladigimiz sutunlari columa ekledik icine attik
        try 
        {
            while (sonEklenenFaturaSonuc.next()) 
            {
                faturaSatir[0] = sonEklenenFaturaSonuc.getString("Fatura_KayitNo");
                faturaSatir[1] = sonEklenenFaturaSonuc.getString("Fatura_Turu");
                faturaSatir[2] = sonEklenenFaturaSonuc.getString("Fatura_Tarihi");
                faturaSatir[3] = sonEklenenFaturaSonuc.getString("Fatura_OdemeTarihi");
                faturaSatir[4] = sonEklenenFaturaSonuc.getString("Fatura_Miktari");
                faturaSatir[5] = sonEklenenFaturaSonuc.getString("Fatura_Dekont");
                FaturaModel.addRow(faturaSatir);//yukarida tanimladigimiz satirlari rowsa ekledik 		
            }

            //garanti suresi azalan urunler
            ResultSet azalanUrunlerSonuc = baglanti.GarantiSuresiAzalanUrunler();
            GarantiBelgesiModel.setRowCount(0);//varsa eski tablo sifirlanir yani temizlenir
            GarantiBelgesiModel.setColumnIdentifiers(garantiBelgesiSutun);
            while (azalanUrunlerSonuc.next()) 
            { //geri donen tablonun kayitlari null olana kadar ekleme yapılır
                garantiBelgesiSatir[0] = azalanUrunlerSonuc.getString("GarantiBelge_KayitNo");
                garantiBelgesiSatir[1] = azalanUrunlerSonuc.getString("GarantiBelge_Turu");
                garantiBelgesiSatir[2] = azalanUrunlerSonuc.getString("GarantiBelge_Markasi");
                garantiBelgesiSatir[3] = azalanUrunlerSonuc.getString("GarantiBelge_Modeli");
                garantiBelgesiSatir[4] = azalanUrunlerSonuc.getString("GarantiBelge_Adi");
                garantiBelgesiSatir[5] = azalanUrunlerSonuc.getString("GarantiBelge_SeriNo");
                garantiBelgesiSatir[6] = azalanUrunlerSonuc.getString("GarantiBelge_GarantiBitisTarihi");
                garantiBelgesiSatir[7] = azalanUrunlerSonuc.getString("GarantiBelge_Faturasi");
                GarantiBelgesiModel.addRow(garantiBelgesiSatir);//yukarida tanimladigimiz satirlari rowsa ekledik 
                //!!! burada formun desing kısmından model kısmına gelip oraya modelimizin konudu yazdık tablo böyle çalışıyor
            }
        } 
        catch (SQLException e) 
        {
            // TODO Auto-generated catch block
            System.out.println("Hata"+e);//hatayı konsola yazdirir
        }
    }
    private void FormunIconunuAyarla() 
    {
        //formun iconunu ayarlar anaform classinin icindeki Evim.jpg resmini alir
        Image Evim = new ImageIcon(AnaForm.class.getResource("Evim.jpg")).getImage();
        setIconImage(Evim);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnFaturaIslemleri;
    private javax.swing.JButton BtnGarantiBelgesiIslemleri;
    private javax.swing.JButton BtnTabloyuYenile;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables

}
