
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

public class FaturaDuzenlemeFormu extends javax.swing.JFrame {

    private DefaultTableModel FaturaModel = new DefaultTableModel();
    private Object[] faturaSutun = {"Fatura Kayit No", "Fatura Turu", "Fatura Tarihi", "Fatura Odeme Tarihi",
        "Fatura Miktari", "Odemeye Ait Dekont"};//sutun isimlerini yazmak icin bir object olusturuyoruz
    private Object[] faturaSatir = new Object[6];
    private FaturaIslemleri faturaIslemleri = new FaturaIslemleri();
    private Fatura fatura = new Fatura();

    public FaturaDuzenlemeFormu() {
        initComponents();
        JTextFieldDateEditor editor = (JTextFieldDateEditor) dc_faturaOdemeTarihi.getDateEditor();
        editor.setEnabled(false);//tarih kutusuna veri girişi engellenir
        JTextFieldDateEditor editor1 = (JTextFieldDateEditor) dc_faturaTarihi.getDateEditor();
        editor1.setEnabled(false);

        TablolariGetir();
        FormunIconunuAyarla();
        txt_faturaDekont.setEditable(false);//dekont textine yazma islemine izin vermez
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        BtnTemizle = new javax.swing.JButton();
        BtnFaturaGoster = new javax.swing.JButton();
        txt_faturaNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_faturaMiktari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_faturaDekont = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbx_faturaTuru = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        dc_faturaTarihi = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        dc_faturaOdemeTarihi = new com.toedter.calendar.JDateChooser();
        btnFaturaListele = new javax.swing.JButton();
        PanelMevcutFaturalar = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        BtnFaturaGuncelle = new javax.swing.JButton();
        BtnFaturaSil = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fatura Duzenleme Formu");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(116, 212, 192));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnTemizle.setBackground(new java.awt.Color(255, 216, 166));
        BtnTemizle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnTemizle.setText("Temizle");
        BtnTemizle.setMaximumSize(new java.awt.Dimension(125, 23));
        BtnTemizle.setMinimumSize(new java.awt.Dimension(125, 23));
        BtnTemizle.setPreferredSize(new java.awt.Dimension(135, 23));
        BtnTemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTemizleActionPerformed(evt);
            }
        });
        jPanel1.add(BtnTemizle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 140, 30));

        BtnFaturaGoster.setBackground(new java.awt.Color(255, 216, 166));
        BtnFaturaGoster.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnFaturaGoster.setText("Faturayı Goster");
        BtnFaturaGoster.setEnabled(false);
        BtnFaturaGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFaturaGosterActionPerformed(evt);
            }
        });
        jPanel1.add(BtnFaturaGoster, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 140, 30));
        jPanel1.add(txt_faturaNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 156, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Fatura Kayit No:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txt_faturaMiktari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_faturaMiktariKeyTyped(evt);
            }
        });
        jPanel1.add(txt_faturaMiktari, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 156, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Fatura Turu:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        txt_faturaDekont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_faturaDekontMouseClicked(evt);
            }
        });
        jPanel1.add(txt_faturaDekont, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 156, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Fatura Tarihi:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Fatura Odeme Tarihi:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        cmbx_faturaTuru.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elektrik", "Telefon", "Su", "Dogal Gaz", "Digerleri" }));
        jPanel1.add(cmbx_faturaTuru, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 156, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Fatura Miktari:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 10));

        dc_faturaTarihi.setBackground(new java.awt.Color(116, 212, 192));
        jPanel1.add(dc_faturaTarihi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 156, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Fatura Ait Dekont:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        dc_faturaOdemeTarihi.setBackground(new java.awt.Color(116, 212, 192));
        jPanel1.add(dc_faturaOdemeTarihi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 156, -1));

        btnFaturaListele.setBackground(new java.awt.Color(255, 216, 166));
        btnFaturaListele.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFaturaListele.setText("Faturayi Listele");
        btnFaturaListele.setPreferredSize(new java.awt.Dimension(135, 23));
        btnFaturaListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFaturaListeleActionPerformed(evt);
            }
        });
        jPanel1.add(btnFaturaListele, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 140, 30));

        jTable3.setModel(FaturaModel);
        jTable3.setEnabled(false);
        PanelMevcutFaturalar.setViewportView(jTable3);

        jPanel1.add(PanelMevcutFaturalar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 708, 118));

        BtnFaturaGuncelle.setBackground(new java.awt.Color(255, 216, 166));
        BtnFaturaGuncelle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnFaturaGuncelle.setText("Faturayi Guncelle");
        BtnFaturaGuncelle.setEnabled(false);
        BtnFaturaGuncelle.setMaximumSize(new java.awt.Dimension(125, 23));
        BtnFaturaGuncelle.setMinimumSize(new java.awt.Dimension(125, 23));
        BtnFaturaGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFaturaGuncelleActionPerformed(evt);
            }
        });
        jPanel1.add(BtnFaturaGuncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 140, 30));

        BtnFaturaSil.setBackground(new java.awt.Color(255, 216, 166));
        BtnFaturaSil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnFaturaSil.setText("Faturayi Sil");
        BtnFaturaSil.setEnabled(false);
        BtnFaturaSil.setMaximumSize(new java.awt.Dimension(125, 23));
        BtnFaturaSil.setMinimumSize(new java.awt.Dimension(125, 23));
        BtnFaturaSil.setPreferredSize(new java.awt.Dimension(135, 23));
        BtnFaturaSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFaturaSilActionPerformed(evt);
            }
        });
        jPanel1.add(BtnFaturaSil, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 140, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Mevcut Faturalar(Azalan Sıralama)");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));
        jLabel1.getAccessibleContext().setAccessibleName("Mevcut Faturalar (Azalan Sıralama)");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnFaturaGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFaturaGosterActionPerformed

      try {
            //acilacak dosyanın yolu verilir 
            File file = new File(txt_faturaDekont.getText());
            if (!Desktop.isDesktopSupported()) // destkleniyor mu desteklenmiyor mu kontrolu yapilir
            {
                System.out.println("Dosya Turu Deklenemiyor");
                return;
            }
            Desktop desktop = Desktop.getDesktop();
            if (file.exists()) //dosyanin olup olmadigi kontrol edilir
            {
                desktop.open(file); //dosya varsa acilir  
            } else//Dosya yolu yoksa bulunamadi uyarisi verilir
            {
                JOptionPane.showMessageDialog(null, "Dosya Yolu Bulunamadi! ");
            }
        } catch (IOException e) {
            e.printStackTrace();//Bu yontem, aynı e nesnesinin mesajini ve ayrica istisnanin olustugu satir numarasini yazdirir.
        }
    }//GEN-LAST:event_BtnFaturaGosterActionPerformed

    private void btnFaturaListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFaturaListeleActionPerformed

        try {
            ResultSet sonuc = faturaIslemleri.FaturaListele(Integer.parseInt(txt_faturaNo.getText()));//resultset geri doner.
            if (!sonuc.isBeforeFirst())//sonucun boş olup olmadığını kontrol eder
            {
                JOptionPane.showMessageDialog(null, "İstediğiniz kayıt numarasında fatura bulunamamiştir !");
            } else {
                while (sonuc.next()) {
                    txt_faturaNo.setText(sonuc.getString("Fatura_KayitNo"));
                    txt_faturaMiktari.setText(sonuc.getString("Fatura_Miktari"));
                    txt_faturaDekont.setText(sonuc.getString("Fatura_Dekont"));
                    cmbx_faturaTuru.setSelectedItem(sonuc.getString("Fatura_Turu"));

                    String faturaTarihi = sonuc.getString("Fatura_Tarihi");
                    Date date = new SimpleDateFormat("yyyy-MM-dd").parse(faturaTarihi);//++ yyyy-mm-dd formatına cevirerek date nesnesine atılır++
                    dc_faturaTarihi.setDate(date);//++olusan date nesnesi date choosere verilir ve fatura tarihi gosterilir

                    String odemeTarihi = sonuc.getString("Fatura_OdemeTarihi");//tarihi jchoosera çekmek için ilk bir stringe çekiyoruz sonra alttarafta pars edip ekliyoruz++
                    Date date1 = new SimpleDateFormat("yyyy-MM-dd").parse(odemeTarihi);
                    dc_faturaOdemeTarihi.setDate(date1);

                    JOptionPane.showMessageDialog(null, "Kaydınız Başarıyla Listelenmistir!");
                    txt_faturaNo.setEnabled(false);  ///Gerekli ayarlamalar yapilir
                    BtnFaturaGuncelle.setEnabled(true);
                    BtnFaturaSil.setEnabled(true);
                    BtnFaturaGoster.setEnabled(true);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lütfen Kayıt Numarası Giriniz! ");
        }
    }//GEN-LAST:event_btnFaturaListeleActionPerformed

    private void BtnFaturaSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFaturaSilActionPerformed
        try {
            FaturaModel.setRowCount(0); //Tablo sıfırlanır 
            faturaIslemleri.FaturaSil(Integer.parseInt(txt_faturaNo.getText()));//fatura islemlerin sınıfındaki sil metoduna fatura no gonderilir ve ilgili fatura silinir
            TablolariGetir();//tabloyu sildikten sonra güncellenir 
            Temizle();//ilgili alanlar temizlenir
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Fatura Silinemedi! ");
        }

    }//GEN-LAST:event_BtnFaturaSilActionPerformed

    private void BtnFaturaGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFaturaGuncelleActionPerformed
        try {
            fatura.setFatura_KayitNo(Integer.parseInt(txt_faturaNo.getText()));
            fatura.setFatura_Turu(cmbx_faturaTuru.getSelectedItem().toString());
            fatura.setFatura_Miktari(Integer.parseInt(txt_faturaMiktari.getText()));
            fatura.setFatura_Dekont((txt_faturaDekont.getText()).replace("\\", "/"));
            fatura.setFatura_OdemeTarihi(TarihDonustur(dc_faturaOdemeTarihi.getDate()));
            fatura.setFatura_Tarihi(TarihDonustur(dc_faturaTarihi.getDate()));
            faturaIslemleri.FaturaGuncelle(fatura);//guncellenecek olan fatura fatura islemlerindeki fatura guncelleye gonderilir ve guncellenir

            TablolariGetir();//guncellenme sonrasında datagrid en son tablo cekilir
            Temizle();//formda doldurulan alanlar temizlenir
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Fatura Güncellenemedi! ");
        }
    }//GEN-LAST:event_BtnFaturaGuncelleActionPerformed

    private void BtnTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTemizleActionPerformed

        Temizle();//yanlis bir islem yapildiginde formu eski haline getirmek icin
    }//GEN-LAST:event_BtnTemizleActionPerformed

    private void txt_faturaDekontMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_faturaDekontMouseClicked

        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF Images", "png", "gif");//Fitreliyoruz
        fileChooser.setFileFilter(filter);
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));//Gecerli projenin dosya yolu
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            txt_faturaDekont.setText(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_txt_faturaDekontMouseClicked

    private void txt_faturaMiktariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_faturaMiktariKeyTyped

        //sadece sayi girmeye izin verir
        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar) || (vChar == KeyEvent.VK_BACK_SPACE) || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_faturaMiktariKeyTyped

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FaturaDuzenlemeFormu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FaturaDuzenlemeFormu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FaturaDuzenlemeFormu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FaturaDuzenlemeFormu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FaturaDuzenlemeFormu().setVisible(true);
            }
        });
    }

    private void Temizle() {
        try {
            //islem bittikten sonra form ilk haline sevrilir
            txt_faturaDekont.setText("");
            txt_faturaMiktari.setText("");
            txt_faturaNo.setText("");

            cmbx_faturaTuru.setSelectedIndex(0);
            txt_faturaNo.setEnabled(true);
            BtnFaturaSil.setEnabled(false);
            BtnFaturaGuncelle.setEnabled(false);
            BtnFaturaGoster.setEnabled(false);

            JTextFieldDateEditor editor = (JTextFieldDateEditor) dc_faturaOdemeTarihi.getDateEditor();
            JTextFieldDateEditor editor1 = (JTextFieldDateEditor) dc_faturaTarihi.getDateEditor();
            editor1.setText(""); //data chooserler bosaltilir
            editor.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Tablo Temizlenemedi! ");
        }

    }

    private void TablolariGetir() {
        FaturaModel.setRowCount(0);
        try {
            VeritabaniBaglanti baglanti = new VeritabaniBaglanti();//veritabaninda sinifindan bir nesne olusturuldu
            ResultSet sonEklenenFaturaSonuc = baglanti.SonEklenenFaturalar();//Sinifta bulunan SonEklenenFaturalar fonksiyonu cagrildi ve degiskene atandi
            FaturaModel.setColumnIdentifiers(faturaSutun);//yukarda tanımladıgimiz sutunlari columa ekledik icine attik
            while (sonEklenenFaturaSonuc.next()) //Son eklenen faturaya kadar döngüde next fonksiyonunu kullanarak döner 
            {
                faturaSatir[0] = sonEklenenFaturaSonuc.getString("Fatura_KayitNo");
                faturaSatir[1] = sonEklenenFaturaSonuc.getString("Fatura_Turu");
                faturaSatir[2] = sonEklenenFaturaSonuc.getString("Fatura_Tarihi");
                faturaSatir[3] = sonEklenenFaturaSonuc.getString("Fatura_OdemeTarihi");
                faturaSatir[4] = sonEklenenFaturaSonuc.getString("Fatura_Miktari");
                faturaSatir[5] = sonEklenenFaturaSonuc.getString("Fatura_Dekont");
                FaturaModel.addRow(faturaSatir);//yukarida taımladığımız satirları rowsa ekledik 		
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tablo Getirilemedi! ");
        }
    }

    private void FormunIconunuAyarla() {
        Image Evim = new ImageIcon(FaturaDuzenlemeFormu.class.getResource("Evim.jpg")).getImage();//resmi çektik burada classin ismi yazılacak burada ilk ilgili class için 
        setIconImage(Evim);
    }

   private String TarihDonustur(Date tarih) //varsayılan degeri private değil bu yüzden private yapılıyor
   {
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");//tarihi  veritabanina eklemek için uygun formata çevirmek için kodlar 
        String faturaTarihi = format.format(dc_faturaTarihi.getDate());//verilen tarihi istenilen formatta cevirir
        return faturaTarihi;//cevrilmis string tarihi geri doner                        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnFaturaGoster;
    private javax.swing.JButton BtnFaturaGuncelle;
    private javax.swing.JButton BtnFaturaSil;
    private javax.swing.JButton BtnTemizle;
    private javax.swing.JScrollPane PanelMevcutFaturalar;
    private javax.swing.JButton btnFaturaListele;
    private javax.swing.JComboBox<String> cmbx_faturaTuru;
    private com.toedter.calendar.JDateChooser dc_faturaOdemeTarihi;
    private com.toedter.calendar.JDateChooser dc_faturaTarihi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField txt_faturaDekont;
    private javax.swing.JTextField txt_faturaMiktari;
    private javax.swing.JTextField txt_faturaNo;
    // End of variables declaration//GEN-END:variables
}
