
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hydon
 */
public class GarantiBelgesiEklemeFormu extends javax.swing.JFrame {

    GarantiBelgesi garantiBelgesi = new GarantiBelgesi();
    GarantiBelgesiIslemleri garantiBelgesiIslemleri = new GarantiBelgesiIslemleri();

    public GarantiBelgesiEklemeFormu() {
        EnSonKayitNosunuCek();
        FormunIconunuAyarla();
        dc_garantiBitisTarihi.getDateEditor().setEnabled(false);//takvime elle giriş engellenir
        txt_fatura.setEditable(false);//dosya yolu elle giriş engellenir
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        dc_garantiBitisTarihi = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        BtnGarantiBelgesiEkleme = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_belgeNo = new javax.swing.JTextField();
        txt_marka = new javax.swing.JTextField();
        txt_model = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_urunAdi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_seriNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_fatura = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbx_urunTuru = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Garanti Belgesi Ekleme Formu");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(116, 212, 192));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Urunun Adi:");

        dc_garantiBitisTarihi.setBackground(new java.awt.Color(116, 212, 192));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Urunun Seri No:");

        BtnGarantiBelgesiEkleme.setBackground(new java.awt.Color(255, 216, 166));
        BtnGarantiBelgesiEkleme.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnGarantiBelgesiEkleme.setText("Garanti Belgesi Ekle");
        BtnGarantiBelgesiEkleme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGarantiBelgesiEklemeActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Garanti Bitis Tarihi:");
        jLabel7.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Urunun Faturasi");

        txt_belgeNo.setText("1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Garanti Belge No:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Urunun Turu:");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Urunun Markasi:");

        txt_fatura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_faturaMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Urunun Modeli:");

        cmbx_urunTuru.setBackground(new java.awt.Color(255, 216, 166));
        cmbx_urunTuru.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Telefon", "Bilgisayar", "Bilgisayar Birimleri", "Televizyon", "Beyaz Esya", "Ev Aletleri", "Mobilya", "Aksesuar", "Diger" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(47, 47, 47)
                        .addComponent(txt_urunAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(24, 24, 24)
                        .addComponent(txt_seriNo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(5, 5, 5)
                        .addComponent(dc_garantiBitisTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(23, 23, 23)
                        .addComponent(txt_fatura, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(BtnGarantiBelgesiEkleme, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addComponent(txt_belgeNo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(cmbx_urunTuru, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(21, 21, 21)
                        .addComponent(txt_marka, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(txt_model, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txt_belgeNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cmbx_urunTuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txt_marka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txt_model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txt_urunAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txt_seriNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dc_garantiBitisTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txt_fatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(BtnGarantiBelgesiEkleme)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGarantiBelgesiEklemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGarantiBelgesiEklemeActionPerformed

        try {
            if (txt_belgeNo.getText().isEmpty() || txt_fatura.getText().isEmpty() || txt_marka.getText().isEmpty() || txt_model.getText().isEmpty() || txt_seriNo.getText().isEmpty()
                    || txt_urunAdi.getText().isEmpty() || dc_garantiBitisTarihi.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Hiç Bir Alan Boş Geçilemez!");
            } else {
                garantiBelgesi.setGarantiBelge_KayitNo(Integer.parseInt(txt_belgeNo.getText()));
                garantiBelgesi.setGarantiBelge_Markasi(txt_marka.getText());
                garantiBelgesi.setGarantiBelge_Turu(cmbx_urunTuru.getSelectedItem().toString());
                garantiBelgesi.setGarantiBelge_Modeli(txt_model.getText());
                garantiBelgesi.setGarantiBelge_Adi(txt_urunAdi.getText());
                garantiBelgesi.setGarantiBelge_SeriNo(txt_seriNo.getText());
                garantiBelgesi.setGarantiBelge_Faturasi(txt_fatura.getText().replace("\\", "/"));
                garantiBelgesi.setGarantiBelge_GarantiBitisTarihi(TarihDonustur(dc_garantiBitisTarihi.getDate()));
                garantiBelgesiIslemleri.GarantiBelgesiEkle(garantiBelgesi);
                JOptionPane.showMessageDialog(null, " Kaydınız Başarıyla Tamamlanmıştır! ");
                Temizle();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Garanti Belgesi Ekleme İşlemi Gerçekleştirilemedi! ");
        }

    }//GEN-LAST:event_BtnGarantiBelgesiEklemeActionPerformed

    private void txt_faturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_faturaMouseClicked
 //fatura dekontunun yolu alinir
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF Images", "png", "gif");//Fitreliyoruz
        fileChooser.setFileFilter(filter);
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));//Gecerli projenin dosya yolu
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) 
        {
            File selectedFile = fileChooser.getSelectedFile();
            try 
            {
                txt_fatura.setText(selectedFile.getCanonicalPath());
            } 
            catch (IOException ex) 
            {
                     JOptionPane.showMessageDialog(null, "Garanti Belgesi Dekont Seçme İşlemi Gerçekleştirilemedi! "+ex);

                // JOptionPane.showMessageDialog(null, "Dekont Seçme  İşlemi Gerçekleştirilemedi! ");
               // Logger.getLogger(FaturaEklemeFormu.class.getName()).log(Level.SEVERE, null, ex);// loglama islemininde ornegi olsun diye loglama yapildi
            }
        }
    }//GEN-LAST:event_txt_faturaMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GarantiBelgesiEklemeFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GarantiBelgesiEklemeFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GarantiBelgesiEklemeFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GarantiBelgesiEklemeFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GarantiBelgesiEklemeFormu().setVisible(true);
            }
        });
    }

    private void EnSonKayitNosunuCek() {
        initComponents();
        txt_belgeNo.setEnabled(false);

        try {
            VeritabaniBaglanti baglanti = new VeritabaniBaglanti();
            ResultSet res = baglanti.GarantiSonKayit();
            while (res.next()) {
                txt_belgeNo.setText(String.valueOf(res.getInt("GarantiBelge_KayitNo") + 1));//en son kayitnosunu bulup bir artiriyor
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Son Kayit Getirilemedi Lütfen Yöneticinize Başvurun.");

        }
    }

    private void FormunIconunuAyarla() {
        //resmi çektik burada classin ismi yazılacak burada ilk ilgili class için 
        Image Evim = new ImageIcon(GarantiBelgesiEklemeFormu.class.getResource("Evim.jpg")).getImage();
        setIconImage(Evim);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

  

    private String TarihDonustur(Date tarih) {
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");//tarih formatını veritabanına eklemek için gerekli kodlar
        String faturaTarihi = format.format(tarih);
        return faturaTarihi;
    }

    private void Temizle() {
        txt_fatura.setText("");
        txt_marka.setText("");
        txt_model.setText("");
        txt_seriNo.setText("");
        txt_urunAdi.setText("");
        cmbx_urunTuru.setSelectedIndex(0);
        EnSonKayitNosunuCek();//kayit numarasi degisecek
        JTextFieldDateEditor editor = (JTextFieldDateEditor) dc_garantiBitisTarihi.getDateEditor();
        editor.setText("");//eklendikten sonra boşaltıyoruz
        editor.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGarantiBelgesiEkleme;
    private javax.swing.JComboBox<String> cmbx_urunTuru;
    private com.toedter.calendar.JDateChooser dc_garantiBitisTarihi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_belgeNo;
    private javax.swing.JTextField txt_fatura;
    private javax.swing.JTextField txt_marka;
    private javax.swing.JTextField txt_model;
    private javax.swing.JTextField txt_seriNo;
    private javax.swing.JTextField txt_urunAdi;
    // End of variables declaration//GEN-END:variables

}
